name: the_djenggot
description:
  "The djenggot is a mobile application that helps people to manage their finances
  and track their expenses. It provides a user-friendly interface and various features to make
  financial management easier."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_speed_dial: ^7.0.0
  go_router: ^14.8.1
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.1
  sqflite: ^2.4.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  fl_chart: ^0.64.0
  image: ^4.5.4
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  share_plus: ^7.0.2
  file_picker: ^10.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # Comment this if you want release mode
    - assets/dummy_images/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100

# App Icon Configuration
flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

# Splash Screen Configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app_icon.png
  branding: assets/images/app_icon.png
  branding_dark: assets/images/app_icon.png

  android_12:
    image: assets/images/app_icon.png
    icon_background_color: "#FFFFFF"

  web: false
