@startuml settings_tab_flow
title The Djenggot - Settings Tab Flow

start

:Display Settings Screen;

if (User Action?) then (Manage Menu Types)
  :Open Menu Type Management Screen;
  if (Action?) then (Add Type)
    :Create New
     Menu Type;
    :Select Icon;
    :Save Menu Type;
  elseif (Action?) then (Edit Type)
    :Modify Menu
     Type Details;
    :Save Changes;
  elseif (Action?) then (Delete Type)
    :Confirm Deletion;
    :Remove Menu Type;
  endif
  
elseif (User Action?) then (Manage Stock Types)
  :Open Stock Type Management Screen;
  if (Action?) then (Add Type)
    :Create New
     Stock Type;
    :Select Icon;
    :Define Units;
    :Save Stock Type;
  elseif (Action?) then (Edit Type)
    :Modify Stock
     Type Details;
    :Save Changes;
  elseif (Action?) then (Delete Type)
    :Confirm Deletion;
    :Remove Stock Type;
  endif
  
elseif (User Action?) then (Manage Transaction Types)
  :Open Transaction Type Management Screen;
  if (Action?) then (Add Type)
    :Create New
     Transaction Type;
    :Select Icon;
    :Save Transaction Type;
  elseif (Action?) then (Edit Type)
    :Modify Transaction
     Type Details;
    :Save Changes;
  elseif (Action?) then (Delete Type)
    :Confirm Deletion;
    :Remove Transaction Type;
  endif
  
elseif (User Action?) then (Export Database)
  :Request Storage Permissions;
  :Select Export Location;
  :Export Database File;
  
elseif (User Action?) then (Import Database)
  :Request Storage Permissions;
  :Select Database File;
  :Import Database Data;
  
elseif (User Action?) then (Report Bug)
  :Open Email Application;
  :Enter Bug Details;
  :Send Report;
endif

stop
@enduml
